# This is very experimental and only sometimes working.

Vagrant.configure("2") do |config|

  config.vm.box = "mitchellh/boot2docker"

  config.vm.provider "virtualbox" do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in TinyCore Linux, so tell Vagrant that so it can be smarter.
    v.name                  = 'ember-app-kit'
    v.check_guest_additions = false
    v.functional_vboxsf     = false
    v.memory                = 1024 * 8
    v.cpus                  = 4
  end

  # b2d doesn't support NFS
  config.nfs.functional = false

  config.vm.network "forwarded_port", guest: 8000,  host: 8000  # App
  config.vm.network "forwarded_port", guest: 35729, host: 35729 # Livereload

end
